# Generated by Django 4.1.5 on 2023-01-16 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api_example", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Paradigm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Programmer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("languages", models.ManyToManyField(to="api_example.language")),
            ],
        ),
        migrations.AlterField(
            model_name="language",
            name="paradigm",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api_example.paradigm"
            ),
        ),
    ]
